# example/build.yaml
targets:
  $default:
    builders:
      dart_easy_json:easy_json_builder:
        options:
          build_extensions:
            "^lib/{{}}.dart": "lib/generated/{{}}.easy.dart"
